/**
 * Co-create avatars with pre-converted base64 URLs
 * Generated by scripts/convert-avatars.ts
 */

export interface Avatar {
  id: string
  name: string
  username: string
  image: string
  base64Url?: string
  httpUrl?: string
}

// Import the converted avatars
import avatarsData from './avatars-converted.json'

export const AVATARS: Avatar[] = avatarsData

// Helper function to get avatar by username
export function getAvatarByUsername(username: string): Avatar | undefined {
  return AVATARS.find(a => a.username.toLowerCase() === username.toLowerCase())
}

// Helper function to get avatar base64 URL
export function getAvatarBase64(username: string): string | undefined {
  const avatar = getAvatarByUsername(username)
  return avatar?.base64Url
}

// Helper function to get avatar HTTP URL (for BytePlus multi-character)
export function getAvatarHttpUrl(username: string): string | undefined {
  const avatar = getAvatarByUsername(username)
  return avatar?.httpUrl
}
